# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-02-07 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200207_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 2, 7, 14, 45, 17, 413082, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
